level-09/college_portal/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: "static_pages#index"
resources :sections, only: [:index, :new, :create]
resources :students, only: [:index, :new, :create, :show]
resources :departments, only: [:index, :create, :new]
end

level-09/college_portal/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

level-09/college_portal/app/models/department.rb
class Department < ApplicationRecord
has_many :sections, dependent: :destroy
has_many :students, dependent: :destroy
validates :name, presence: true, uniqueness: true

before_save :to_upper
def to_upper
    self.name = self.name.upcase
end
end

level-09/college_portal/app/models/section.rb
class Section < ApplicationRecord
belongs_to :department
has_many :students, dependent: :destroy
validates :name, presence: true, uniqueness: true
before_save :to_upper
def to_upper
    self.name = self.name.upcase
end
end

level-09/college_portal/app/models/student.rb
class Student < ApplicationRecord
belongs_to :department
belongs_to :section
validates :section_id , presence: true
validates :department_id , presence: true
validates :name, presence: true , uniqueness: true
validate :validate_section_mapping

  before_create :generate_roll_no
  private

  def validate_section_mapping
    section = Section.find_by_id(section_id)
	department=Department.find_by_id(department_id)
	if section.nil?
	errors.add(:section,"sections field cant be empty")
    elsif section.department_id != department_id
      errors.add(:section, "Selected section doesn't belongs to selected department")
    end
  end
def generate_roll_no
    max_count = Student.count
    department_name = department.name.downcase.gsub(/\s/, '-')
    section_name = section.name.downcase.gsub(/\s/, '-')
    self.roll_no = "#{department_name}-#{section_name}-#{max_count+1}"
  end
end

level-09/college_portal/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

level-09/college_portal/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

level-09/college_portal/app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
before_action :authenticate_user!
  def index
    @departments = Department.all
  end

  def new
	unless current_user.admin?
    flash[:danger] = "You are not allowed to access this page."
    redirect_to root_path
  end
    @department = Department.new
  end

  def create
unless current_user.admin?
    flash[:danger] = "You are not allowed to access this page."
    redirect_to root_path
  end
    @department = Department.new(department_params)
    if @department.save
      redirect_to action: "index"
    else
 flash[:danger] = @department.errors.values.join(', ')
      render "new"
    end
  end

  private

  def department_params
    params[:department].permit(:name)
  end
end

level-09/college_portal/app/controllers/sections_controller.rb
class SectionsController < ApplicationController
before_action :authenticate_user!
  def index
    if params[:department_id]
      @sections = Section.where(department_id: params[:department_id]).all
    else
      @sections = Section.all
    end
  end

  def new
unless current_user.admin?
    flash[:danger] = "You are not allowed to access this page."
    redirect_to root_path
  end
    @section = Section.new
    @department_collection = Department.all.collect { |p| [p.name, p.id] }
  end

  def create
 unless current_user.admin?
    flash[:danger] = "You are not allowed to access this page."
    redirect_to root_path
  end
    @section = Section.new(section_params)
    if @section.save
      redirect_to action: "index"
    else
 flash[:danger] = @department.errors.values.join(', ')
      render "new"
    end
  end

  private

  def section_params
    params[:section].permit(:name, :department_id)
  end
end

level-09/college_portal/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

level-09/college_portal/app/controllers/students_controller.rb
class StudentsController < ApplicationController
before_action :authenticate_user!
def index
if params[:department_id] and params[:section_id]
 @students = Student.where(department_id: params[:department_id],section_id: params[:section_id]).all
else
@students=Student.all
end
end
def show
    @student = Student.find(params[:id])
end
def new
unless current_user.admin?
    flash[:danger] = "You are not allowed to access this page."
    redirect_to root_path
  end
      @student=Student.new
      @department_col=Department.all.collect { |p| [p.name, p.id] }
      @section_col=Section.all.collect { |p| [p.name, p.id] }
end
def create
 unless current_user.admin?
    flash[:danger] = "You are not allowed to access this page."
    redirect_to root_path
  end
    @student = Student.new(student_params)
    if @student.save
      redirect_to action: "index"
    else
      flash[:danger] = @student.errors.values.join(', ')
    redirect_to action: "new"
    end
end
private
def student_params
    params[:student].permit(:name,:roll_no, :email, :section_id, :department_id)
  end
end

level-09/college_portal/app/helpers/application_helper.rb
module ApplicationHelper
end

level-09/college_portal/app/helpers/departments_helper.rb
module DepartmentsHelper
end

level-09/college_portal/app/helpers/sections_helper.rb
module SectionsHelper
end

level-09/college_portal/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

level-09/college_portal/app/helpers/students_helper.rb
module StudentsHelper
end

level-09/college_portal/app/views/departments/index.html.erb
<div class="row">
  <div class="col-md-10">
    <h2>Departments</h2>
  </div>
<% if current_user.admin? %>
    <div class="col-md-2">
      <a class="btn btn-primary float-right" href="<%=new_department_path%>" role="button">Create</a>
    </div>
  <% end %>
</div>

<br/>

<ul class="list-group">
  <% @departments.each do |department| %>
    <li class="list-group-item">
<a href="<%= sections_path(department_id: department.id) %>"><%= department.name %></a></li>
  <% end %>
</ul>

level-09/college_portal/app/views/departments/new.html.erb
<h2>Create Department</h2>

<%= form_for(@department) do |f| %>
  <div class="form-group">
    <label>Name</label>
    <%= f.text_field :name, class: "form-control", placeholder: "Department Name", required: true %><br/>
    <%= f.submit text: "create", class: "btn btn-primary" %>
  </div>
<% end %>

level-09/college_portal/app/views/sections/index.html.erb
<div class="row">
  <div class="col-md-10">
    <h2>Sections</h2>
  </div>
<% if current_user.admin? %>
  <div class="col-md-2">
    <a class="btn btn-primary float-right" href="<%= new_section_path %>" role="button">Create</a>
  </div>
<% end %>
</div>

<br/>

<ul class="list-group">
  <% @sections.each do |section| %>
    <li class="list-group-item"><a href="<%= students_path(department_id: section.department_id,section_id: section.id) %>"><%= section.name %></a></li>
  <% end %>
</ul>

level-09/college_portal/app/views/sections/new.html.erb
<h2>Create Section</h2>

<%= form_for(@section) do |f| %>
  <div class="form-group">
    <label>Name</label>
    <%= f.text_field :name, class: "form-control", placeholder: "Section Name", required: true%>
    <br/>
    <label>Department</label>
    <%= f.select :department_id, @department_collection, { prompt: 'Select Department' }, class: "form-control", required: true%>
    <br/>
    <%= f.submit text: "create", class: "btn btn-primary"%>
  </div>
<% end %>

level-09/college_portal/app/views/static_pages/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Welcome to College Portal</h1>
  <p class="lead">A unified view of college directory</p>
  <hr class="my-4">
  <p>You can see listing of Departments and Sections and create them as and when needed.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Let's get started</a>
  </p>
</div>

level-09/college_portal/app/views/students/index.html.erb
<div class="row">
  <div class="col-md-10">
    <h2>Students</h2>
  </div>
<% if current_user.admin? %>
  <div class="col-md-2">
    <a class="btn btn-primary float-right" href="<%= new_student_path %>" role="button">Create</a>
  </div>
<% end %>
</div>

<br/>

<ul class="list-group">
  <% @students.each do |student| %>
    <li class="list-group-item"><a href="<%= student_path(id: student.id)%> "><%= student.name %></a></li>
  <% end %>
</ul>

level-09/college_portal/app/views/students/new.html.erb
<h2>Create Students</h2>

<%= form_for(@student) do |f| %>
  <div class="form-group">
    <label>Name</label>
    <%= f.text_field :name, class: "form-control", placeholder: "Student Name", required: true%>
    <br/>
    <label>Department</label>
    <%= f.select :department_id, @department_col, { prompt: 'Select Department' }, class: "form-control", required: true%>
 <label>Email</label>
    <%= f.text_field :email, class: "form-control", placeholder: "Student email", required: true%>
    <br/>
     <label>Section</label>
    <%= f.select :section_id, @section_col, { prompt: 'Select Section' }, class: "form-control", required: true%>
    <br/>
    <%= f.submit text: "create", class: "btn btn-primary"%>
  </div>
<% end %>

level-09/college_portal/app/views/students/show.html.erb
<h2><%= @student.name %></h2>
 <h4>Department</h4>
 <div class="list-group">
 <p  class="list-group-item list-group-item-action list-group-item-dark"> <%= @student.department.name %> </p>

</div>
 <h4>Section</h4>
<div class="list-group">

 <p class="list-group-item list-group-item-action list-group-item-dark"><%= @student.section.name %> </p>
</div>